 docker pull registry.redhat.io/openshift3/apb-base:v3.11.16
 docker pull registry.redhat.io/openshift3/apb-tools:v3.11.16
 docker pull registry.redhat.io/openshift3/automation-broker-apb:v3.11.16
 docker pull registry.redhat.io/openshift3/csi-attacher:v3.11.16
 docker pull registry.redhat.io/openshift3/csi-driver-registrar:v3.11.16
 docker pull registry.redhat.io/openshift3/csi-livenessprobe:v3.11.16
 docker pull registry.redhat.io/openshift3/csi-provisioner:v3.11.16
 docker pull registry.redhat.io/openshift3/grafana:v3.11.16
 docker pull registry.redhat.io/openshift3/image-inspector:v3.11.16
 docker pull registry.redhat.io/openshift3/local-storage-provisioner:v3.11.16
 docker pull registry.redhat.io/openshift3/manila-provisioner:v3.11.16
 docker pull registry.redhat.io/openshift3/mariadb-apb:v3.11.16
 docker pull registry.redhat.io/openshift3/mediawiki:v3.11.16
 docker pull registry.redhat.io/openshift3/mediawiki-apb:v3.11.16
 docker pull registry.redhat.io/openshift3/mysql-apb:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-ansible:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-ansible-service-broker:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-cli:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-cluster-autoscaler:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-cluster-capacity:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-cluster-monitoring-operator:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-console:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-configmap-reloader:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-control-plane:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-deployer:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-descheduler:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-docker-builder:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-docker-registry:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-efs-provisioner:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-egress-dns-proxy:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-egress-http-proxy:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-egress-router:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-haproxy-router:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-hyperkube:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-hypershift:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-keepalived-ipfailover:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-kube-rbac-proxy:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-kube-state-metrics:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-metrics-server:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-node:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-node-problem-detector:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-operator-lifecycle-manager:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-ovn-kubernetes:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-pod:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-prometheus-config-reloader:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-prometheus-operator:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-recycler:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-service-catalog:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-template-service-broker:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-tests:v3.11.16
 docker pull registry.redhat.io/openshift3/ose-web-console:v3.11.16
 docker pull registry.redhat.io/openshift3/postgresql-apb:v3.11.16
 docker pull registry.redhat.io/openshift3/registry-console:v3.11.16
 docker pull registry.redhat.io/openshift3/snapshot-controller:v3.11.16
 docker pull registry.redhat.io/openshift3/snapshot-provisioner:v3.11.16
 docker pull registry.redhat.io/rhel7/etcd:3.2.22
