docker pull registry.redhat.io/jboss-amq-6/amq63-openshift
docker pull registry.redhat.io/jboss-datagrid-7/datagrid71-openshift
docker pull registry.redhat.io/jboss-datagrid-7/datagrid71-client-openshift
docker pull registry.redhat.io/jboss-datavirt-6/datavirt63-openshift
docker pull registry.redhat.io/jboss-datavirt-6/datavirt63-driver-openshift
docker pull registry.redhat.io/jboss-decisionserver-6/decisionserver64-openshift
docker pull registry.redhat.io/jboss-processserver-6/processserver64-openshift
docker pull registry.redhat.io/jboss-eap-6/eap64-openshift
docker pull registry.redhat.io/jboss-eap-7/eap71-openshift
docker pull registry.redhat.io/jboss-webserver-3/webserver31-tomcat7-openshift
docker pull registry.redhat.io/jboss-webserver-3/webserver31-tomcat8-openshift
docker pull registry.redhat.io/openshift3/jenkins-2-rhel7
docker pull registry.redhat.io/openshift3/jenkins-agent-maven-35-rhel7
docker pull registry.redhat.io/openshift3/jenkins-agent-nodejs-8-rhel7
docker pull registry.redhat.io/openshift3/jenkins-slave-base-rhel7
docker pull registry.redhat.io/openshift3/jenkins-slave-maven-rhel7
docker pull registry.redhat.io/openshift3/jenkins-slave-nodejs-rhel7
docker pull registry.redhat.io/rhscl/mongodb-32-rhel7
docker pull registry.redhat.io/rhscl/mysql-57-rhel7
docker pull registry.redhat.io/rhscl/perl-524-rhel7
docker pull registry.redhat.io/rhscl/php-56-rhel7:
docker pull registry.redhat.io/rhscl/postgresql-95-rhel7
docker pull registry.redhat.io/rhscl/python-35-rhel7
docker pull registry.redhat.io/redhat-sso-7/sso70-openshift
docker pull registry.redhat.io/rhscl/ruby-24-rhel7
docker pull registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
docker pull registry.redhat.io/redhat-sso-7/sso71-openshift
docker pull registry.redhat.io/rhscl/nodejs-6-rhel7
docker pull registry.redhat.io/rhscl/mariadb-101-rhel7
docker pull registry.redhat.io/openshift3/jenkins-slave-nodejs-rhel7
echo "Done"
